#!/bin/bash

python sd_stylize.py --config "/root/autodl-tmp/configs/CPSD/config_tau_attn_5_tau_feat_5_share_attn_[0]_share_resnet_[0].yaml"
python sd_stylize.py --config "/root/autodl-tmp/configs/CPSD/config_tau_attn_5_tau_feat_5_share_attn_[0]_share_resnet_[0, 1, 2, 3, 4].yaml"
python sd_stylize.py --config "/root/autodl-tmp/configs/CPSD/config_tau_attn_5_tau_feat_5_share_attn_[0]_share_resnet_[4, 5, 6, 7, 8].yaml"
python sd_stylize.py --config "/root/autodl-tmp/configs/CPSD/config_tau_attn_5_tau_feat_5_share_attn_[0]_share_resnet_[0, 1, 2, 3, 4, 5, 6, 7, 8].yaml"
python sd_stylize.py --config "/root/autodl-tmp/configs/CPSD/config_tau_attn_5_tau_feat_5_share_attn_[0, 1, 2, 3, 4]_share_resnet_[0].yaml"
python sd_stylize.py --config "/root/autodl-tmp/configs/CPSD/config_tau_attn_5_tau_feat_5_share_attn_[0, 1, 2, 3, 4]_share_resnet_[0, 1, 2, 3, 4].yaml"
python sd_stylize.py --config "/root/autodl-tmp/configs/CPSD/config_tau_attn_5_tau_feat_5_share_attn_[0, 1, 2, 3, 4]_share_resnet_[4, 5, 6, 7, 8].yaml"
python sd_stylize.py --config "/root/autodl-tmp/configs/CPSD/config_tau_attn_5_tau_feat_5_share_attn_[0, 1, 2, 3, 4]_share_resnet_[0, 1, 2, 3, 4, 5, 6, 7, 8].yaml"
python sd_stylize.py --config "/root/autodl-tmp/configs/CPSD/config_tau_attn_5_tau_feat_5_share_attn_[4, 5, 6, 7, 8]_share_resnet_[0].yaml"
python sd_stylize.py --config "/root/autodl-tmp/configs/CPSD/config_tau_attn_5_tau_feat_5_share_attn_[4, 5, 6, 7, 8]_share_resnet_[0, 1, 2, 3, 4].yaml"
python sd_stylize.py --config "/root/autodl-tmp/configs/CPSD/config_tau_attn_5_tau_feat_5_share_attn_[4, 5, 6, 7, 8]_share_resnet_[4, 5, 6, 7, 8].yaml"
python sd_stylize.py --config "/root/autodl-tmp/configs/CPSD/config_tau_attn_5_tau_feat_5_share_attn_[4, 5, 6, 7, 8]_share_resnet_[0, 1, 2, 3, 4, 5, 6, 7, 8].yaml"
python sd_stylize.py --config "/root/autodl-tmp/configs/CPSD/config_tau_attn_5_tau_feat_5_share_attn_[0, 1, 2, 3, 4, 5, 6, 7, 8]_share_resnet_[0].yaml"
python sd_stylize.py --config "/root/autodl-tmp/configs/CPSD/config_tau_attn_5_tau_feat_5_share_attn_[0, 1, 2, 3, 4, 5, 6, 7, 8]_share_resnet_[0, 1, 2, 3, 4].yaml"
python sd_stylize.py --config "/root/autodl-tmp/configs/CPSD/config_tau_attn_5_tau_feat_5_share_attn_[0, 1, 2, 3, 4, 5, 6, 7, 8]_share_resnet_[4, 5, 6, 7, 8].yaml"
python sd_stylize.py --config "/root/autodl-tmp/configs/CPSD/config_tau_attn_5_tau_feat_5_share_attn_[0, 1, 2, 3, 4, 5, 6, 7, 8]_share_resnet_[0, 1, 2, 3, 4, 5, 6, 7, 8].yaml"
python sd_stylize.py --config "/root/autodl-tmp/configs/CPSD/config_tau_attn_5_tau_feat_10_share_attn_[0]_share_resnet_[0].yaml"
python sd_stylize.py --config "/root/autodl-tmp/configs/CPSD/config_tau_attn_5_tau_feat_10_share_attn_[0]_share_resnet_[0, 1, 2, 3, 4].yaml"
python sd_stylize.py --config "/root/autodl-tmp/configs/CPSD/config_tau_attn_5_tau_feat_10_share_attn_[0]_share_resnet_[4, 5, 6, 7, 8].yaml"
python sd_stylize.py --config "/root/autodl-tmp/configs/CPSD/config_tau_attn_5_tau_feat_10_share_attn_[0]_share_resnet_[0, 1, 2, 3, 4, 5, 6, 7, 8].yaml"
python sd_stylize.py --config "/root/autodl-tmp/configs/CPSD/config_tau_attn_5_tau_feat_10_share_attn_[0, 1, 2, 3, 4]_share_resnet_[0].yaml"
python sd_stylize.py --config "/root/autodl-tmp/configs/CPSD/config_tau_attn_5_tau_feat_10_share_attn_[0, 1, 2, 3, 4]_share_resnet_[0, 1, 2, 3, 4].yaml"
python sd_stylize.py --config "/root/autodl-tmp/configs/CPSD/config_tau_attn_5_tau_feat_10_share_attn_[0, 1, 2, 3, 4]_share_resnet_[4, 5, 6, 7, 8].yaml"
python sd_stylize.py --config "/root/autodl-tmp/configs/CPSD/config_tau_attn_5_tau_feat_10_share_attn_[0, 1, 2, 3, 4]_share_resnet_[0, 1, 2, 3, 4, 5, 6, 7, 8].yaml"
python sd_stylize.py --config "/root/autodl-tmp/configs/CPSD/config_tau_attn_5_tau_feat_10_share_attn_[4, 5, 6, 7, 8]_share_resnet_[0].yaml"
python sd_stylize.py --config "/root/autodl-tmp/configs/CPSD/config_tau_attn_5_tau_feat_10_share_attn_[4, 5, 6, 7, 8]_share_resnet_[0, 1, 2, 3, 4].yaml"
python sd_stylize.py --config "/root/autodl-tmp/configs/CPSD/config_tau_attn_5_tau_feat_10_share_attn_[4, 5, 6, 7, 8]_share_resnet_[4, 5, 6, 7, 8].yaml"
python sd_stylize.py --config "/root/autodl-tmp/configs/CPSD/config_tau_attn_5_tau_feat_10_share_attn_[4, 5, 6, 7, 8]_share_resnet_[0, 1, 2, 3, 4, 5, 6, 7, 8].yaml"
python sd_stylize.py --config "/root/autodl-tmp/configs/CPSD/config_tau_attn_5_tau_feat_10_share_attn_[0, 1, 2, 3, 4, 5, 6, 7, 8]_share_resnet_[0].yaml"
python sd_stylize.py --config "/root/autodl-tmp/configs/CPSD/config_tau_attn_5_tau_feat_10_share_attn_[0, 1, 2, 3, 4, 5, 6, 7, 8]_share_resnet_[0, 1, 2, 3, 4].yaml"
python sd_stylize.py --config "/root/autodl-tmp/configs/CPSD/config_tau_attn_5_tau_feat_10_share_attn_[0, 1, 2, 3, 4, 5, 6, 7, 8]_share_resnet_[4, 5, 6, 7, 8].yaml"
python sd_stylize.py --config "/root/autodl-tmp/configs/CPSD/config_tau_attn_5_tau_feat_10_share_attn_[0, 1, 2, 3, 4, 5, 6, 7, 8]_share_resnet_[0, 1, 2, 3, 4, 5, 6, 7, 8].yaml"
python sd_stylize.py --config "/root/autodl-tmp/configs/CPSD/config_tau_attn_10_tau_feat_5_share_attn_[0]_share_resnet_[0].yaml"
python sd_stylize.py --config "/root/autodl-tmp/configs/CPSD/config_tau_attn_10_tau_feat_5_share_attn_[0]_share_resnet_[0, 1, 2, 3, 4].yaml"
python sd_stylize.py --config "/root/autodl-tmp/configs/CPSD/config_tau_attn_10_tau_feat_5_share_attn_[0]_share_resnet_[4, 5, 6, 7, 8].yaml"
python sd_stylize.py --config "/root/autodl-tmp/configs/CPSD/config_tau_attn_10_tau_feat_5_share_attn_[0]_share_resnet_[0, 1, 2, 3, 4, 5, 6, 7, 8].yaml"
python sd_stylize.py --config "/root/autodl-tmp/configs/CPSD/config_tau_attn_10_tau_feat_5_share_attn_[0, 1, 2, 3, 4]_share_resnet_[0].yaml"
python sd_stylize.py --config "/root/autodl-tmp/configs/CPSD/config_tau_attn_10_tau_feat_5_share_attn_[0, 1, 2, 3, 4]_share_resnet_[0, 1, 2, 3, 4].yaml"
python sd_stylize.py --config "/root/autodl-tmp/configs/CPSD/config_tau_attn_10_tau_feat_5_share_attn_[0, 1, 2, 3, 4]_share_resnet_[4, 5, 6, 7, 8].yaml"
python sd_stylize.py --config "/root/autodl-tmp/configs/CPSD/config_tau_attn_10_tau_feat_5_share_attn_[0, 1, 2, 3, 4]_share_resnet_[0, 1, 2, 3, 4, 5, 6, 7, 8].yaml"
python sd_stylize.py --config "/root/autodl-tmp/configs/CPSD/config_tau_attn_10_tau_feat_5_share_attn_[4, 5, 6, 7, 8]_share_resnet_[0].yaml"
python sd_stylize.py --config "/root/autodl-tmp/configs/CPSD/config_tau_attn_10_tau_feat_5_share_attn_[4, 5, 6, 7, 8]_share_resnet_[0, 1, 2, 3, 4].yaml"
python sd_stylize.py --config "/root/autodl-tmp/configs/CPSD/config_tau_attn_10_tau_feat_5_share_attn_[4, 5, 6, 7, 8]_share_resnet_[4, 5, 6, 7, 8].yaml"
python sd_stylize.py --config "/root/autodl-tmp/configs/CPSD/config_tau_attn_10_tau_feat_5_share_attn_[4, 5, 6, 7, 8]_share_resnet_[0, 1, 2, 3, 4, 5, 6, 7, 8].yaml"
python sd_stylize.py --config "/root/autodl-tmp/configs/CPSD/config_tau_attn_10_tau_feat_5_share_attn_[0, 1, 2, 3, 4, 5, 6, 7, 8]_share_resnet_[0].yaml"
python sd_stylize.py --config "/root/autodl-tmp/configs/CPSD/config_tau_attn_10_tau_feat_5_share_attn_[0, 1, 2, 3, 4, 5, 6, 7, 8]_share_resnet_[0, 1, 2, 3, 4].yaml"
python sd_stylize.py --config "/root/autodl-tmp/configs/CPSD/config_tau_attn_10_tau_feat_5_share_attn_[0, 1, 2, 3, 4, 5, 6, 7, 8]_share_resnet_[4, 5, 6, 7, 8].yaml"
python sd_stylize.py --config "/root/autodl-tmp/configs/CPSD/config_tau_attn_10_tau_feat_5_share_attn_[0, 1, 2, 3, 4, 5, 6, 7, 8]_share_resnet_[0, 1, 2, 3, 4, 5, 6, 7, 8].yaml"
python sd_stylize.py --config "/root/autodl-tmp/configs/CPSD/config_tau_attn_10_tau_feat_10_share_attn_[0]_share_resnet_[0].yaml"
python sd_stylize.py --config "/root/autodl-tmp/configs/CPSD/config_tau_attn_10_tau_feat_10_share_attn_[0]_share_resnet_[0, 1, 2, 3, 4].yaml"
python sd_stylize.py --config "/root/autodl-tmp/configs/CPSD/config_tau_attn_10_tau_feat_10_share_attn_[0]_share_resnet_[4, 5, 6, 7, 8].yaml"
python sd_stylize.py --config "/root/autodl-tmp/configs/CPSD/config_tau_attn_10_tau_feat_10_share_attn_[0]_share_resnet_[0, 1, 2, 3, 4, 5, 6, 7, 8].yaml"
python sd_stylize.py --config "/root/autodl-tmp/configs/CPSD/config_tau_attn_10_tau_feat_10_share_attn_[0, 1, 2, 3, 4]_share_resnet_[0].yaml"
python sd_stylize.py --config "/root/autodl-tmp/configs/CPSD/config_tau_attn_10_tau_feat_10_share_attn_[0, 1, 2, 3, 4]_share_resnet_[0, 1, 2, 3, 4].yaml"
python sd_stylize.py --config "/root/autodl-tmp/configs/CPSD/config_tau_attn_10_tau_feat_10_share_attn_[0, 1, 2, 3, 4]_share_resnet_[4, 5, 6, 7, 8].yaml"
python sd_stylize.py --config "/root/autodl-tmp/configs/CPSD/config_tau_attn_10_tau_feat_10_share_attn_[0, 1, 2, 3, 4]_share_resnet_[0, 1, 2, 3, 4, 5, 6, 7, 8].yaml"
python sd_stylize.py --config "/root/autodl-tmp/configs/CPSD/config_tau_attn_10_tau_feat_10_share_attn_[4, 5, 6, 7, 8]_share_resnet_[0].yaml"
python sd_stylize.py --config "/root/autodl-tmp/configs/CPSD/config_tau_attn_10_tau_feat_10_share_attn_[4, 5, 6, 7, 8]_share_resnet_[0, 1, 2, 3, 4].yaml"
python sd_stylize.py --config "/root/autodl-tmp/configs/CPSD/config_tau_attn_10_tau_feat_10_share_attn_[4, 5, 6, 7, 8]_share_resnet_[4, 5, 6, 7, 8].yaml"
python sd_stylize.py --config "/root/autodl-tmp/configs/CPSD/config_tau_attn_10_tau_feat_10_share_attn_[4, 5, 6, 7, 8]_share_resnet_[0, 1, 2, 3, 4, 5, 6, 7, 8].yaml"
python sd_stylize.py --config "/root/autodl-tmp/configs/CPSD/config_tau_attn_10_tau_feat_10_share_attn_[0, 1, 2, 3, 4, 5, 6, 7, 8]_share_resnet_[0].yaml"
python sd_stylize.py --config "/root/autodl-tmp/configs/CPSD/config_tau_attn_10_tau_feat_10_share_attn_[0, 1, 2, 3, 4, 5, 6, 7, 8]_share_resnet_[0, 1, 2, 3, 4].yaml"
python sd_stylize.py --config "/root/autodl-tmp/configs/CPSD/config_tau_attn_10_tau_feat_10_share_attn_[0, 1, 2, 3, 4, 5, 6, 7, 8]_share_resnet_[4, 5, 6, 7, 8].yaml"
python sd_stylize.py --config "/root/autodl-tmp/configs/CPSD/config_tau_attn_10_tau_feat_10_share_attn_[0, 1, 2, 3, 4, 5, 6, 7, 8]_share_resnet_[0, 1, 2, 3, 4, 5, 6, 7, 8].yaml"
